version: '3.7'
services:
  aws:
    build:
      dockerfile: aws.Dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: AKIAJXIKOGN62JQVDDFA
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: af-south-1
      AWS_DEFAULT_REGION: af-south-1
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: AKIAJXIKOGN62JQVDDFA
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: af-south-1
      AWS_DEFAULT_REGION: af-south-1
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  website:
   build:
    context: .
   ports:
    - 80:80
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
  integration-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb

